minimum_pre_commit_version: "3.7.0"
default_install_hook_types:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: polinko-markdownlint-docs
        name: polinko markdownlint docs
        entry: make lint-docs
        language: system
        pass_filenames: false
        stages: [pre-commit, manual]
