# Portfolio mockup composed environment.
PORTFOLIO_MOCKUP_ENV = \
	PORTFOLIO_MOCKUP_DIR="$(PORTFOLIO_MOCKUP_DIR)" \
	PORTFOLIO_MOCKUP_PORT="$(PORTFOLIO_MOCKUP_PORT)" \
	PORTFOLIO_MOCKUP_URL="$(PORTFOLIO_MOCKUP_URL)" \
	PORTFOLIO_MOCKUP_PID_FILE="$(PORTFOLIO_MOCKUP_PID_FILE)" \
	PORTFOLIO_MOCKUP_LOG="$(PORTFOLIO_MOCKUP_LOG)" \
	PORTFOLIO_MOCKUP_LAUNCHER_PYTHON="$(PORTFOLIO_MOCKUP_LAUNCHER_PYTHON)" \
	PYTHON="$(PYTHON)"
