# Repo-managed caffeinate environment assembly.
CAFFEINATE_ENV = \
	CAFFEINATE_RUNTIME_ROOT="$(CAFFEINATE_RUNTIME_ROOT)" \
	CAFFEINATE_STATE_DIR="$(CAFFEINATE_STATE_DIR)" \
	CAFFEINATE_PID_FILE="$(CAFFEINATE_PID_FILE)" \
	CAFFEINATE_LOG="$(CAFFEINATE_LOG)" \
	CAFFEINATE_META_FILE="$(CAFFEINATE_META_FILE)" \
	CAFFEINATE_ACTIVITY_FILE="$(CAFFEINATE_ACTIVITY_FILE)" \
	CAFFEINATE_REPO_SLUG="$(CAFFEINATE_REPO_SLUG)" \
	CAFFEINATE_ACTIVE_WINDOW_SECONDS="$(CAFFEINATE_ACTIVE_WINDOW_SECONDS)" \
	CAFFEINATE_ALLOW_GLOBAL_CLEANUP="$(CAFFEINATE_ALLOW_GLOBAL_CLEANUP)" \
	CAFFEINATE_CMD="$(CAFFEINATE_CMD)" \
	CAFFEINATE_MATCH_PATTERN="$(CAFFEINATE_MATCH_PATTERN)" \
	CAFFEINATE_LAUNCHER_PYTHON="$(CAFFEINATE_LAUNCHER_PYTHON)"
repo_activity = $(CAFFEINATE_ENV) CAFFEINATE_ACTIVITY_LABEL="$(1)" CAFFEINATE_ACTIVITY_TARGET="$(2)" bash "$(CAFFEINATE_SCRIPT)" activity
