# OpenAI account composed environment.
OPENAI_ACCOUNT_ENV = \
	OPENAI_API_BASE_URL="$(OPENAI_API_BASE_URL)" \
	OPENAI_ADMIN_KEY_ENV="$(OPENAI_ADMIN_KEY_ENV)" \
	OPENAI_ACCOUNT_TIMEOUT="$(OPENAI_ACCOUNT_TIMEOUT)" \
	OPENAI_COST_DAYS="$(OPENAI_COST_DAYS)" \
	OPENAI_COST_BUCKET_WIDTH="$(OPENAI_COST_BUCKET_WIDTH)" \
	OPENAI_COST_GROUP_BY="$(OPENAI_COST_GROUP_BY)" \
	OPENAI_USAGE_DAYS="$(OPENAI_USAGE_DAYS)" \
	OPENAI_USAGE_BUCKET_WIDTH="$(OPENAI_USAGE_BUCKET_WIDTH)" \
	OPENAI_USAGE_KIND="$(OPENAI_USAGE_KIND)" \
	OPENAI_USAGE_GROUP_BY="$(OPENAI_USAGE_GROUP_BY)" \
	OPENAI_PROJECT_ID="$(OPENAI_PROJECT_ID)" \
	OPENAI_LIMITS_PAGE_SIZE="$(OPENAI_LIMITS_PAGE_SIZE)"
