# Shared Makefile configuration.
VENV ?= .venv
PYTHON ?= $(shell \
	if [ -x ./$(VENV)/bin/python3.14 ] && ./$(VENV)/bin/python3.14 -V >/dev/null 2>&1; then \
		echo ./$(VENV)/bin/python3.14; \
	elif [ -x ./$(VENV)/bin/python ] && ./$(VENV)/bin/python -V >/dev/null 2>&1; then \
		echo ./$(VENV)/bin/python; \
	else \
		echo python3; \
	fi)
DOCKER ?= docker
DOCKER_IMAGE ?= polinko:dev
DOCKER_PORT ?= 8000
DEV_HOST ?= 127.0.0.1
DEV_BACKEND_PORT ?= 8000
CLI_ENTRYPOINT ?= main.py
ASGI_APP ?= server:app
DEV_API_DOCS_URL ?= http://$(DEV_HOST):$(DEV_BACKEND_PORT)/docs
DEV_VIZ_URL ?= http://$(DEV_HOST):$(DEV_BACKEND_PORT)/viz/pass-fail
DEV_PORTFOLIO_URL ?= http://$(DEV_HOST):$(DEV_BACKEND_PORT)/portfolio
ifneq ($(origin FRONTEND_DIR), undefined)
PORTFOLIO_APP_DIR ?= $(FRONTEND_DIR)
else
PORTFOLIO_APP_DIR ?= apps/portfolio
endif
FRONTEND_DIR ?= $(PORTFOLIO_APP_DIR)
PORTFOLIO_STATIC_DIR ?= public/portfolio
PORTFOLIO_MOCKUP_DIR ?= docs/peanut/assets/portfolio-mockups
PORTFOLIO_MOCKUP_PORT ?= 8765
PORTFOLIO_MOCKUP_URL ?= http://127.0.0.1:$(PORTFOLIO_MOCKUP_PORT)/landing-mockups.html
PORTFOLIO_LAUNCH ?= none
PORTFOLIO_PLAYWRIGHT_SESSION ?= $(PLAYWRIGHT_SESSION)
OPENAI_LIMITS_URL ?= https://platform.openai.com/settings/organization/limits
OPENAI_USAGE_URL ?= https://platform.openai.com/settings/organization/usage
OPENAI_BILLING_URL ?= https://platform.openai.com/settings/organization/billing/overview
ENV_FILE ?= .env
K6_BASE_URL ?= http://127.0.0.1:8000
K6_VUS ?= 3
K6_DURATION ?= 10s
TRIVY_SEVERITY ?= HIGH,CRITICAL
GATE_PORT ?= 8066
GATE_BASE_URL ?= http://127.0.0.1:$(GATE_PORT)
GATE_SESSION_DB ?= /tmp/polinko-quality-gate-sessions.db
GATE_VECTOR_DB ?= /tmp/polinko-quality-gate-vector.db
SMOKE_PORT ?= 8067
SMOKE_BASE_URL ?= http://127.0.0.1:$(SMOKE_PORT)
SMOKE_HISTORY_DB ?= /tmp/polinko-eval-smoke-history.db
SMOKE_MEMORY_DB ?= /tmp/polinko-eval-smoke-memory.db
SMOKE_VECTOR_DB ?= /tmp/polinko-eval-smoke-vector.db
HALLUCINATION_EVAL_MODE ?= judge
HALLUCINATION_JUDGE_MODEL ?= gpt-4.1-mini
HALLUCINATION_JUDGE_API_KEY_ENV ?= OPENAI_API_KEY
HALLUCINATION_JUDGE_BASE_URL ?=
HALLUCINATION_MIN_ACCEPTABLE_SCORE ?= 5
STYLE_CASE_ATTEMPTS ?= 1
STYLE_MIN_PASS_ATTEMPTS ?= 1
RETRIEVAL_REQUEST_RETRIES ?= 2
RETRIEVAL_REQUEST_RETRY_DELAY_MS ?= 750
CLIP_AB_SOURCE_TYPES ?= image
OCR_HANDWRITING_CASES ?= .local/eval_cases/ocr_handwriting_eval_cases.json
OCR_SAFETY_CASES ?= docs/eval/beta_2_0/ocr_safety_eval_cases.json
CGPT_EXPORT_ROOT ?=
CGPT_EXPORT_ROOT_DEFAULT ?=
CGPT_EXPORT_OUTPUT_DIR ?= .local/eval_cases
OCR_CASES_FROM_EXPORT_ARGS ?=
OCR_TRANSCRIPT_CASES_ALL ?= .local/eval_cases/ocr_transcript_cases_all.json
OCR_TRANSCRIPT_CASES_GROWTH ?= .local/eval_cases/ocr_transcript_cases_growth.json
OCR_TRANSCRIPT_CASES_HANDWRITING ?= .local/eval_cases/ocr_handwriting_from_transcripts.json
OCR_TRANSCRIPT_CASES_TYPED ?= .local/eval_cases/ocr_typed_from_transcripts.json
OCR_TRANSCRIPT_CASES_ILLUSTRATION ?= .local/eval_cases/ocr_illustration_from_transcripts.json
OCR_TRANSCRIPT_CASES_HANDWRITING_BENCHMARK ?= .local/eval_cases/ocr_handwriting_benchmark_cases.json
OCR_TRANSCRIPT_CASES_TYPED_BENCHMARK ?= .local/eval_cases/ocr_typed_benchmark_cases.json
OCR_TRANSCRIPT_CASES_ILLUSTRATION_BENCHMARK ?= .local/eval_cases/ocr_illustration_benchmark_cases.json
OCR_TRANSCRIPT_CASES ?= $(OCR_TRANSCRIPT_CASES_ALL)
OCR_TRANSCRIPT_REVIEW ?= .local/eval_cases/ocr_transcript_cases_review.json
OCR_TRANSCRIPT_REVIEW_PREV ?= .local/eval_cases/ocr_transcript_cases_review_prev.json
OCR_TRANSCRIPT_DELTA_MD ?= .local/eval_cases/ocr_transcript_cases_delta.md
OCR_TRANSCRIPT_DELTA_JSON ?= .local/eval_cases/ocr_transcript_cases_delta.json
OCR_GENERALIZATION_CANDIDATES ?= .local/eval_cases/ocr_generalization_candidates.json
OCR_GENERALIZATION_REVIEW ?= .local/eval_cases/ocr_generalization_review.json
OCR_GENERALIZATION_REVIEW_MAX_CASES ?= 24
OCR_GENERALIZATION_REVIEW_MAX_PER_CONVERSATION ?= 2
OCR_GENERALIZATION_REVIEW_INCLUDE_IDS ?=
OCR_HANDWRITING_BENCHMARK_TOP_K ?= 6
OCR_HANDWRITING_BENCHMARK_MIN_ANCHORS ?= 3
OCR_TYPED_BENCHMARK_TOP_K ?= 8
OCR_TYPED_BENCHMARK_MIN_ANCHORS ?= 3
OCR_ILLUSTRATION_BENCHMARK_TOP_K ?= 6
OCR_ILLUSTRATION_BENCHMARK_MIN_ANCHORS ?= 2
OCR_STABILITY_RUNS ?= 5
OCR_STABILITY_OCR_RETRIES ?= 2
OCR_STABILITY_OCR_RETRY_DELAY_MS ?= 750
OCR_STABILITY_CASE_DELAY_MS ?= 0
OCR_STABILITY_RATE_LIMIT_COOLDOWN_MS ?= 0
OCR_MAX_CONSEC_RATE_LIMIT_ERRORS ?= 3
OCR_EVAL_TIMEOUT ?= 90
OCR_EVAL_OCR_RETRIES ?= 2
OCR_EVAL_OCR_RETRY_DELAY_MS ?= 750
OCR_STABILITY_OUTPUT ?= .local/eval_reports/ocr_transcript_stability.json
OCR_STABILITY_REPORT_DIR ?= .local/eval_reports/ocr_stability_runs
OCR_GROWTH_MAX_CASES ?= 600
OCR_GROWTH_STABILITY_OUTPUT ?= .local/eval_reports/ocr_growth_stability.json
OCR_GROWTH_STABILITY_REPORT_DIR ?= .local/eval_reports/ocr_growth_stability_runs
OCR_GROWTH_STABILITY_RUNS ?= $(OCR_STABILITY_RUNS)
OCR_GROWTH_METRICS_OUTPUT ?= .local/eval_reports/ocr_growth_metrics.json
OCR_GROWTH_METRICS_MARKDOWN ?= .local/eval_reports/ocr_growth_metrics.md
OCR_GROWTH_FAIL_COHORT_JSON ?= .local/eval_cases/ocr_growth_fail_cohort.json
OCR_GROWTH_FAIL_COHORT_MARKDOWN ?= .local/eval_reports/ocr_growth_fail_cohort.md
OCR_FAIL_COHORT_MIN_RUNS ?= 1
OCR_FAIL_COHORT_INCLUDE_UNSTABLE ?= true
OCR_FAIL_COHORT_REQUIRE_OCR_FRAMING ?= true
OCR_FAIL_COHORT_INCLUDE_EXPLORATORY ?= true
OCR_FAIL_COHORT_EXPLORATORY_MAX_CASES ?= 18
OCR_FOCUS_CASES_JSON ?= .local/eval_cases/ocr_growth_focus_cases.json
OCR_FOCUS_RUNS ?= 3
OCR_FOCUS_MAX_CASES ?= 40
OCR_FOCUS_INCLUDE_FAIL_HISTORY ?= true
OCR_FOCUS_INCLUDE_EXPLORATORY ?= true
OCR_FOCUS_OUTPUT ?= .local/eval_reports/ocr_focus_stability.json
OCR_FOCUS_REPORT_DIR ?= .local/eval_reports/ocr_focus_runs
OCR_FOCUS_FAIL_PATTERNS_JSON ?= .local/eval_reports/ocr_focus_fail_patterns.json
OCR_FOCUS_FAIL_PATTERNS_MD ?= .local/eval_reports/ocr_focus_fail_patterns.md
OCR_FOCUS_OCR_RETRIES ?= 3
OCR_FOCUS_OCR_RETRY_DELAY_MS ?= 1000
OCR_FOCUS_CASE_DELAY_MS ?= 1200
OCR_FOCUS_RATE_LIMIT_COOLDOWN_MS ?= 12000
OCR_FOCUS_SKIP_RECENT_RATE_LIMIT ?= true
OCR_FOCUS_RATE_LIMIT_BACKOFF_SECONDS ?= 900
OCR_GROWTH_LIMIT_RUNS ?= 0
OCR_GROWTH_EVAL_OFFSET ?= 0
OCR_GROWTH_EVAL_MAX_CASES ?= 0
OCR_GROWTH_BATCH_SIZE ?= 40
OCR_GROWTH_OCR_RETRIES ?= 2
OCR_GROWTH_OCR_RETRY_DELAY_MS ?= 750
OCR_GROWTH_CASE_DELAY_MS ?= 0
OCR_GROWTH_RATE_LIMIT_COOLDOWN_MS ?= 0
OCR_GROWTH_BATCH_REPORT_DIR ?= .local/eval_reports/ocr_growth_batched_runs
OCR_GROWTH_BATCH_SUMMARY_JSON ?= .local/eval_reports/ocr_growth_batched_summary.json
OCR_GROWTH_BATCH_SUMMARY_MD ?= .local/eval_reports/ocr_growth_batched_summary.md
OCR_STABILITY_HANDWRITING_BENCHMARK_OUTPUT ?= .local/eval_reports/ocr_handwriting_benchmark_stability.json
OCR_STABILITY_HANDWRITING_BENCHMARK_REPORT_DIR ?= .local/eval_reports/ocr_handwriting_benchmark_runs
OCR_STABILITY_TYPED_BENCHMARK_OUTPUT ?= .local/eval_reports/ocr_typed_benchmark_stability.json
OCR_STABILITY_TYPED_BENCHMARK_REPORT_DIR ?= .local/eval_reports/ocr_typed_benchmark_runs
OCR_STABILITY_ILLUSTRATION_BENCHMARK_OUTPUT ?= .local/eval_reports/ocr_illustration_benchmark_stability.json
OCR_STABILITY_ILLUSTRATION_BENCHMARK_REPORT_DIR ?= .local/eval_reports/ocr_illustration_benchmark_runs
NOTEBOOK_START_PATH ?= output/jupyter-notebook/ocr-eval-live-filters-starter.ipynb
NOTEBOOK_START_PATH_ABS := $(abspath $(NOTEBOOK_START_PATH))
NOTEBOOK_DIR_ABS := $(abspath output/jupyter-notebook)
CAFFEINATE_PID_FILE ?= /tmp/polinko-caffeinate.pid
CAFFEINATE_LOG ?= /tmp/polinko-caffeinate.log
CAFFEINATE_CMD ?= /usr/bin/caffeinate -d -i -m
SERVER_PID_FILE ?= /tmp/polinko-server.pid
SERVER_LOG ?= /tmp/polinko-server.log
EVAL_SIDECAR_PID_FILE ?= /tmp/polinko-eval-sidecar.pid
EVAL_SIDECAR_LOG ?= /tmp/polinko-eval-sidecar.log
EVAL_SIDECAR_TARGET ?= quality-gate-deterministic
EVAL_SIDECAR_MIN_SECONDS ?= 3600
EVAL_SIDECAR_RUNS_DIR ?= .local/eval_runs
EVAL_SIDECAR_CURRENT_FILE ?= $(EVAL_SIDECAR_RUNS_DIR)/eval_sidecar_current.txt
OCR_WORKFLOW_SCRIPT ?= ./tools/run_ocr_workflow.sh
EVAL_SERVER_DAEMON_SCRIPT ?= ./tools/ensure_eval_server_daemon.sh
EVAL_CASE_GUARD_SCRIPT ?= ./tools/eval_case_guard.sh
OCR_EVAL_RUNNER_SCRIPT ?= ./tools/run_eval_ocr_cases.sh
OCR_EVAL_RUNNER_ENV = \
	PYTHON="$(PYTHON)" \
	EVAL_SERVER_DAEMON_SCRIPT="$(EVAL_SERVER_DAEMON_SCRIPT)" \
	OCR_EVAL_TIMEOUT="$(OCR_EVAL_TIMEOUT)" \
	OCR_EVAL_OCR_RETRIES="$(OCR_EVAL_OCR_RETRIES)" \
	OCR_EVAL_OCR_RETRY_DELAY_MS="$(OCR_EVAL_OCR_RETRY_DELAY_MS)" \
	OCR_MAX_CONSEC_RATE_LIMIT_ERRORS="$(OCR_MAX_CONSEC_RATE_LIMIT_ERRORS)"
OCR_STABILITY_RUNNER_SCRIPT ?= ./tools/run_eval_ocr_stability.sh
OCR_STABILITY_RUNNER_ENV = \
	PYTHON="$(PYTHON)" \
	EVAL_SERVER_DAEMON_SCRIPT="$(EVAL_SERVER_DAEMON_SCRIPT)" \
	OCR_EVAL_TIMEOUT="$(OCR_EVAL_TIMEOUT)" \
	OCR_MAX_CONSEC_RATE_LIMIT_ERRORS="$(OCR_MAX_CONSEC_RATE_LIMIT_ERRORS)"
PORTFOLIO_MOCKUP_PID_FILE ?= /tmp/polinko-portfolio-mockups.pid
PORTFOLIO_MOCKUP_LOG ?= /tmp/polinko-portfolio-mockups.log
PLAYWRIGHT_SNAPSHOT_BASE_DIR ?= docs/peanut/assets/screenshots/playwright
PLAYWRIGHT_SNAPSHOT_DAY ?= $(shell date +%d-%m-%y)
PLAYWRIGHT_SESSION ?= polinko
PWCLI_TOOL ?= tools/pwcli_daily.sh
REQUIREMENTS_IN ?= requirements.in
REQUIREMENTS_LOCK ?= requirements.lock
PIP_TOOLS_VERSION ?= 7.5.3
