# GitHub CLI configuration.
GH ?= gh
GITHUB_HEALTH_REPO ?=
GITHUB_HEALTH_RUN_LIMIT ?= 20
GITHUB_HEALTH_PR_LIMIT ?= 20
GITHUB_PR_BASE ?= main
GITHUB_PR_HEAD ?=
GITHUB_PR_TITLE ?=
GITHUB_PR_BODY_FILE ?=
